# Generated by Django 6.0.3 on 2026-05-04 12:09

import astrology.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mental_health', 'Mental Health'), ('marriage', 'Marriage Timing'), ('prosperity_sav', 'Prosperity & Career (SAV)'), ('medical', 'Medical Astrology'), ('btr', 'Birth Time Rectification'), ('parasari', 'Parasari Relationships'), ('navatara', 'Navatara (Nine Stars)'), ('darakaraka', 'Spouse Profile (Jaimini)'), ('planetary_states', 'Planetary Avatars & States'), ('benefic_planets', 'Benefic Planets'), ('malefic_planets', 'Malefic Planets'), ('chart_analysis', 'Chart Analysis'), ('astro_energy', '12-Dimensional Astro Energy'), ('rashi_planets', 'Meaning of the Rashi Planets'), ('lagna_lord', 'Your Lagna Lord Position'), ('challenges', 'Challenges and Learning'), ('d1-chart', 'D1 Chart Context'), ('d9-chart', 'D9 Navamsa Chart Context')], help_text='The astrology insight category this prompt applies to.', max_length=50, unique=True)),
                ('user_prompt', models.TextField(blank=True, help_text="This text will be appended to the end of the AI prompt to guide the AI's focus.")),
                ('is_active', models.BooleanField(default=True, help_text='Disable to ignore this custom prompt.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AstrologyChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mental_health', 'Mental Health'), ('marriage', 'Marriage Timing'), ('prosperity_sav', 'Prosperity & Career (SAV)'), ('medical', 'Medical Astrology'), ('btr', 'Birth Time Rectification'), ('parasari', 'Parasari Relationships'), ('navatara', 'Navatara (Nine Stars)'), ('darakaraka', 'Spouse Profile (Jaimini)'), ('planetary_states', 'Planetary Avatars & States'), ('benefic_planets', 'Benefic Planets'), ('malefic_planets', 'Malefic Planets'), ('chart_analysis', 'Chart Analysis'), ('astro_energy', '12-Dimensional Astro Energy'), ('rashi_planets', 'Meaning of the Rashi Planets'), ('lagna_lord', 'Your Lagna Lord Position'), ('challenges', 'Challenges and Learning'), ('d1-chart', 'D1 Chart Context'), ('d9-chart', 'D9 Navamsa Chart Context')], max_length=50)),
                ('role', models.CharField(choices=[('user', 'User'), ('model', 'Model')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Astrology Chat Message',
                'verbose_name_plural': 'Astrology Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AstrologyDashboardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Astrology Dashboard Access',
                'verbose_name_plural': 'Astrology Dashboard Accesses',
            },
        ),
        migrations.CreateModel(
            name='AstrologyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mental_health', 'Mental Health'), ('marriage', 'Marriage Timing'), ('prosperity_sav', 'Prosperity & Career (SAV)'), ('medical', 'Medical Astrology'), ('btr', 'Birth Time Rectification'), ('parasari', 'Parasari Relationships'), ('navatara', 'Navatara (Nine Stars)'), ('darakaraka', 'Spouse Profile (Jaimini)'), ('planetary_states', 'Planetary Avatars & States'), ('benefic_planets', 'Benefic Planets'), ('malefic_planets', 'Malefic Planets'), ('chart_analysis', 'Chart Analysis'), ('astro_energy', '12-Dimensional Astro Energy'), ('rashi_planets', 'Meaning of the Rashi Planets'), ('lagna_lord', 'Your Lagna Lord Position'), ('challenges', 'Challenges and Learning'), ('d1-chart', 'D1 Chart Context'), ('d9-chart', 'D9 Navamsa Chart Context')], max_length=50)),
                ('insight_text', models.TextField()),
                ('is_transit_dependent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BirthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', astrology.fields.EncryptedCharField(blank=True, max_length=500)),
                ('birth_year', astrology.fields.EncryptedIntegerField()),
                ('birth_month', astrology.fields.EncryptedIntegerField()),
                ('birth_day', astrology.fields.EncryptedIntegerField()),
                ('birth_hour', astrology.fields.EncryptedIntegerField()),
                ('birth_minute', astrology.fields.EncryptedIntegerField()),
                ('city', astrology.fields.EncryptedCharField(max_length=500)),
                ('country_code', astrology.fields.EncryptedCharField(max_length=100)),
                ('timezone_str', astrology.fields.EncryptedCharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NakshatraPredictionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_data', models.JSONField()),
                ('cached_for_date', models.DateField()),
                ('ai_guidance', models.JSONField(blank=True, null=True)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NatalChartCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_details_data', models.JSONField()),
                ('divisional_data', models.JSONField()),
                ('kp_data', models.JSONField(blank=True, null=True)),
                ('dasha_data', models.JSONField(blank=True, null=True)),
                ('ashtakvarga_data', models.JSONField(blank=True, null=True)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransitCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit_data', models.JSONField()),
                ('cached_for_date', models.DateField()),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
