# Generated by Django 6.0.3 on 2026-03-24 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.IntegerField()),
                ('birth_month', models.IntegerField()),
                ('birth_day', models.IntegerField()),
                ('birth_hour', models.IntegerField()),
                ('birth_minute', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=5)),
                ('timezone_str', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birth_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NatalChartCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_details_data', models.JSONField()),
                ('divisional_data', models.JSONField()),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
                ('birth_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='natal_cache', to='astrology.birthprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TransitCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit_data', models.JSONField()),
                ('cached_for_date', models.DateField()),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('birth_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transit_cache', to='astrology.birthprofile')),
            ],
        ),
    ]
