# Generated by Django 6.0.3 on 2026-05-04 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('astrology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologydashboardaccess',
            name='student',
            field=models.ForeignKey(help_text='The student who owns the dashboard.', on_delete=django.db.models.deletion.CASCADE, related_name='astrology_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='astrologydashboardaccess',
            name='teacher',
            field=models.ForeignKey(help_text='The teacher who has been granted access.', on_delete=django.db.models.deletion.CASCADE, related_name='astrology_access_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='birthprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_guest_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='birthprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='astrologyinsight',
            name='birth_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='astrology.birthprofile'),
        ),
        migrations.AddField(
            model_name='astrologychat',
            name='birth_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='astrology.birthprofile'),
        ),
        migrations.AddField(
            model_name='nakshatrapredictioncache',
            name='birth_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nakshatra_prediction_cache', to='astrology.birthprofile'),
        ),
        migrations.AddField(
            model_name='natalchartcache',
            name='birth_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='natal_cache', to='astrology.birthprofile'),
        ),
        migrations.AddField(
            model_name='transitcache',
            name='birth_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transit_cache', to='astrology.birthprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='astrologydashboardaccess',
            unique_together={('student', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='astrologyinsight',
            unique_together={('birth_profile', 'category')},
        ),
    ]
