# Generated by Django 6.0.3 on 2026-03-25 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='natalchartcache',
            name='ashtakvarga_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='natalchartcache',
            name='dasha_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='natalchartcache',
            name='divisional_extended_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='natalchartcache',
            name='kp_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AstrologyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mental_health', 'Mental Health'), ('marriage', 'Marriage Timing'), ('prosperity_sav', 'Prosperity & Career (SAV)'), ('medical', 'Medical Astrology'), ('btr', 'Birth Time Rectification'), ('parasari', 'Parasari Relationships'), ('navatara', 'Navatara (Nine Stars)'), ('darakaraka', 'Spouse Profile (Jaimini)'), ('planetary_states', 'Planetary Avatars & States')], max_length=50)),
                ('insight_text', models.TextField()),
                ('is_transit_dependent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='astrology.birthprofile')),
            ],
            options={
                'unique_together': {('birth_profile', 'category')},
            },
        ),
    ]
