# Generated by Django 6.0.3 on 2026-05-22 13:45

import astrology.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthprofile',
            name='comments',
            field=astrology.fields.EncryptedCharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='birthprofile',
            name='kids',
            field=astrology.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='birthprofile',
            name='marriage_date',
            field=astrology.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
    ]
