# Generated by Django 6.0.3 on 2026-03-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0002_natalchartcache_ashtakvarga_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='natalchartcache',
            name='divisional_extended_data',
        ),
    ]
