# Generated by Django 6.0.3 on 2026-03-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0003_remove_natalchartcache_divisional_extended_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mental_health', 'Mental Health'), ('marriage', 'Marriage Timing'), ('prosperity_sav', 'Prosperity & Career (SAV)'), ('medical', 'Medical Astrology'), ('btr', 'Birth Time Rectification'), ('parasari', 'Parasari Relationships'), ('navatara', 'Navatara (Nine Stars)'), ('darakaraka', 'Spouse Profile (Jaimini)'), ('planetary_states', 'Planetary Avatars & States')], help_text='The astrology insight category this prompt applies to.', max_length=50, unique=True)),
                ('user_prompt', models.TextField(blank=True, help_text="This text will be appended to the end of the AI prompt to guide the AI's focus.")),
                ('is_active', models.BooleanField(default=True, help_text='Disable to ignore this custom prompt.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
