# Generated by Django 6.0.3 on 2026-05-22 13:45

import astrology.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0003_birthprofile_comments_birthprofile_kids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthprofile',
            name='kids',
            field=astrology.fields.EncryptedIntegerField(blank=True, null=True),
        ),
    ]
