# Generated by Django 6.0.3 on 2026-03-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0004_aipromptconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aipromptconfiguration',
            name='category',
            field=models.CharField(choices=[('mental_health', 'Mental Health'), ('marriage', 'Marriage Timing'), ('prosperity_sav', 'Prosperity & Career (SAV)'), ('medical', 'Medical Astrology'), ('btr', 'Birth Time Rectification'), ('parasari', 'Parasari Relationships'), ('navatara', 'Navatara (Nine Stars)'), ('darakaraka', 'Spouse Profile (Jaimini)'), ('planetary_states', 'Planetary Avatars & States'), ('benefic_planets', 'Benefic Planets'), ('malefic_planets', 'Malefic Planets'), ('chart_analysis', 'Chart Analysis'), ('state_of_planets', 'State of Planets'), ('astro_energy', '12-Dimensional Astro Energy'), ('rashi_planets', 'Meaning of the Rashi Planets'), ('lagna_lord', 'Your Lagna Lord Position'), ('challenges', 'Challenges and Learning')], help_text='The astrology insight category this prompt applies to.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='astrologyinsight',
            name='category',
            field=models.CharField(choices=[('mental_health', 'Mental Health'), ('marriage', 'Marriage Timing'), ('prosperity_sav', 'Prosperity & Career (SAV)'), ('medical', 'Medical Astrology'), ('btr', 'Birth Time Rectification'), ('parasari', 'Parasari Relationships'), ('navatara', 'Navatara (Nine Stars)'), ('darakaraka', 'Spouse Profile (Jaimini)'), ('planetary_states', 'Planetary Avatars & States'), ('benefic_planets', 'Benefic Planets'), ('malefic_planets', 'Malefic Planets'), ('chart_analysis', 'Chart Analysis'), ('state_of_planets', 'State of Planets'), ('astro_energy', '12-Dimensional Astro Energy'), ('rashi_planets', 'Meaning of the Rashi Planets'), ('lagna_lord', 'Your Lagna Lord Position'), ('challenges', 'Challenges and Learning')], max_length=50),
        ),
    ]
