# Generated by Django 6.0.3 on 2026-05-22 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0004_alter_birthprofile_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitcache',
            name='birth_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_caches', to='astrology.birthprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='transitcache',
            unique_together={('birth_profile', 'cached_for_date')},
        ),
    ]
