# Generated by Django 6.0.3 on 2026-03-27 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0005_alter_aipromptconfiguration_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aipromptconfiguration',
            name='category',
            field=models.CharField(choices=[('mental_health', 'Mental Health'), ('marriage', 'Marriage Timing'), ('prosperity_sav', 'Prosperity & Career (SAV)'), ('medical', 'Medical Astrology'), ('btr', 'Birth Time Rectification'), ('parasari', 'Parasari Relationships'), ('navatara', 'Navatara (Nine Stars)'), ('darakaraka', 'Spouse Profile (Jaimini)'), ('planetary_states', 'Planetary Avatars & States'), ('benefic_planets', 'Benefic Planets'), ('malefic_planets', 'Malefic Planets'), ('chart_analysis', 'Chart Analysis'), ('astro_energy', '12-Dimensional Astro Energy'), ('rashi_planets', 'Meaning of the Rashi Planets'), ('lagna_lord', 'Your Lagna Lord Position'), ('challenges', 'Challenges and Learning')], help_text='The astrology insight category this prompt applies to.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='astrologyinsight',
            name='category',
            field=models.CharField(choices=[('mental_health', 'Mental Health'), ('marriage', 'Marriage Timing'), ('prosperity_sav', 'Prosperity & Career (SAV)'), ('medical', 'Medical Astrology'), ('btr', 'Birth Time Rectification'), ('parasari', 'Parasari Relationships'), ('navatara', 'Navatara (Nine Stars)'), ('darakaraka', 'Spouse Profile (Jaimini)'), ('planetary_states', 'Planetary Avatars & States'), ('benefic_planets', 'Benefic Planets'), ('malefic_planets', 'Malefic Planets'), ('chart_analysis', 'Chart Analysis'), ('astro_energy', '12-Dimensional Astro Energy'), ('rashi_planets', 'Meaning of the Rashi Planets'), ('lagna_lord', 'Your Lagna Lord Position'), ('challenges', 'Challenges and Learning')], max_length=50),
        ),
        migrations.CreateModel(
            name='AstrologyDashboardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(help_text='The student who owns the dashboard.', on_delete=django.db.models.deletion.CASCADE, related_name='astrology_access_grants', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='The teacher who has been granted access.', on_delete=django.db.models.deletion.CASCADE, related_name='astrology_access_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Astrology Dashboard Access',
                'verbose_name_plural': 'Astrology Dashboard Accesses',
                'unique_together': {('student', 'teacher')},
            },
        ),
    ]
