# Generated by Django 6.0.3 on 2026-04-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0006_astrologydashboardaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstrologyChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mental_health', 'Mental Health'), ('marriage', 'Marriage Timing'), ('prosperity_sav', 'Prosperity & Career (SAV)'), ('medical', 'Medical Astrology'), ('btr', 'Birth Time Rectification'), ('parasari', 'Parasari Relationships'), ('navatara', 'Navatara (Nine Stars)'), ('darakaraka', 'Spouse Profile (Jaimini)'), ('planetary_states', 'Planetary Avatars & States'), ('benefic_planets', 'Benefic Planets'), ('malefic_planets', 'Malefic Planets'), ('chart_analysis', 'Chart Analysis'), ('astro_energy', '12-Dimensional Astro Energy'), ('rashi_planets', 'Meaning of the Rashi Planets'), ('lagna_lord', 'Your Lagna Lord Position'), ('challenges', 'Challenges and Learning')], max_length=50)),
                ('role', models.CharField(choices=[('user', 'User'), ('model', 'Model')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birth_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='astrology.birthprofile')),
            ],
            options={
                'verbose_name': 'Astrology Chat Message',
                'verbose_name_plural': 'Astrology Chat Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
