# Generated by Django 6.0.3 on 2026-04-13 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0007_astrologychat'),
    ]

    operations = [
        migrations.CreateModel(
            name='NakshatraPredictionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_data', models.JSONField()),
                ('cached_for_date', models.DateField()),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('birth_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nakshatra_prediction_cache', to='astrology.birthprofile')),
            ],
        ),
    ]
