# Generated by Django 6.0.3 on 2026-04-21 16:21

import astrology.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0009_birthprofile_created_by_birthprofile_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthprofile',
            name='birth_day',
            field=astrology.fields.EncryptedIntegerField(),
        ),
        migrations.AlterField(
            model_name='birthprofile',
            name='birth_hour',
            field=astrology.fields.EncryptedIntegerField(),
        ),
        migrations.AlterField(
            model_name='birthprofile',
            name='birth_minute',
            field=astrology.fields.EncryptedIntegerField(),
        ),
        migrations.AlterField(
            model_name='birthprofile',
            name='birth_month',
            field=astrology.fields.EncryptedIntegerField(),
        ),
        migrations.AlterField(
            model_name='birthprofile',
            name='birth_year',
            field=astrology.fields.EncryptedIntegerField(),
        ),
        migrations.AlterField(
            model_name='birthprofile',
            name='city',
            field=astrology.fields.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='birthprofile',
            name='country_code',
            field=astrology.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='birthprofile',
            name='guest_name',
            field=astrology.fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='birthprofile',
            name='timezone_str',
            field=astrology.fields.EncryptedCharField(blank=True, max_length=500),
        ),
    ]
