# Generated by Django 6.0.3 on 2026-04-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0011_encrypt_existing_birth_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='nakshatrapredictioncache',
            name='ai_guidance',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
