# Generated by Django 6.0.3 on 2026-06-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0014_alter_aipromptconfiguration_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalCalendarCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('festival_type', models.CharField(default='', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('region', models.CharField(default='', max_length=100)),
                ('calendar_data', models.JSONField()),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Festival Calendar Cache',
                'verbose_name_plural': 'Festival Calendar Caches',
                'unique_together': {('year', 'festival_type', 'language', 'region')},
            },
        ),
    ]
