# Generated by Django 6.0.3 on 2026-06-12 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0015_festivalcalendarcache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AstrologyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('full', 'Full Vedic Astrology Report')], default='full', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('generating', 'Generating'), ('ready', 'Ready for Download'), ('failed', 'Generation Failed')], default='pending', max_length=20)),
                ('report_url', models.URLField(blank=True, max_length=2000)),
                ('preview_content', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='astrology.birthprofile')),
            ],
            options={
                'verbose_name': 'Astrology Report',
                'verbose_name_plural': 'Astrology Reports',
                'unique_together': {('birth_profile', 'report_type')},
            },
        ),
        migrations.CreateModel(
            name='ReportPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('amount_cents', models.IntegerField(help_text='Amount in cents (USD)')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='astrology.astrologyreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Payment',
                'verbose_name_plural': 'Report Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
