# Generated by Django 6.0.3 on 2026-06-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0016_add_report_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologyreport',
            name='preview_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
