# Generated by Django 6.0.3 on 2026-05-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('BOTH', 'Both Student and Teacher'), ('ADMIN', 'Administrator')], max_length=20, null=True),
        ),
    ]
