# Generated by Django 5.2.4 on 2025-09-09 08:00
# Migration to clean up lessons app tables

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_session_user_role_sessionbilling_student_and_more'),
    ]

    operations = [
        # Drop lessons app tables in reverse dependency order
        migrations.RunSQL(
            "DROP TABLE IF EXISTS lessons_conversation CASCADE;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS lessons_learningprogress CASCADE;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS lessons_aisession CASCADE;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS lessons_learningcontext CASCADE;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS lessons_voiceavatar CASCADE;",
            reverse_sql="-- Cannot reverse this operation"
        ),
    ]
