# Generated by Django 6.0.3 on 2026-04-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_oauth_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.RemoveField(
            model_name='session',
            name='student',
        ),
        migrations.RemoveField(
            model_name='session',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='sessionbilling',
            name='session',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teachercertificate',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teachergig',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='AIConversation',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='SessionBilling',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='TeacherCertificate',
        ),
        migrations.DeleteModel(
            name='TeacherGig',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
