# Generated by Django 6.0.3 on 2026-05-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_file_user_remove_session_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
