# Generated by Django 6.0.3 on 2026-05-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('BOTH', 'Both Student and Teacher'), ('ADMIN', 'Administrator')], default='STUDENT', max_length=20),
        ),
    ]
