# Generated by Django 6.0.3 on 2026-05-25 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who owns this family member profile.', on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'family_members',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('spouse', 'Spouse')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(help_text='The member whose relation is being defined', on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='family_tree.familymember')),
                ('relative', models.ForeignKey(help_text='The relative (parent or spouse)', on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='family_tree.familymember')),
            ],
            options={
                'db_table': 'family_tree_relationships',
                'ordering': ['created_at'],
                'unique_together': {('profile', 'relative', 'relationship_type')},
            },
        ),
    ]
