# Generated by Django 6.0.3 on 2026-06-01 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='connected_user',
            field=models.ForeignKey(blank=True, help_text='Optional link to a real registered user of the application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_family_member_nodes', to=settings.AUTH_USER_MODEL),
        ),
    ]
