# Generated by Django 6.0.3 on 2026-05-04 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=250, unique=True)),
                ('content', models.TextField(help_text='Main blog content')),
                ('thumbnail', models.CharField(blank=True, help_text='URL or path to thumbnail image', max_length=500, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for the blog')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When the blog was published', null=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('read_time', models.PositiveIntegerField(default=0, help_text='Estimated read time in minutes')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='accounts.teacherprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['author', '-created_at'], name='blogs_blog_author__b0902b_idx'), models.Index(fields=['status', '-published_at'], name='blogs_blog_status_2b4687_idx'), models.Index(fields=['slug'], name='blogs_blog_slug_d0bba8_idx')],
            },
        ),
    ]
