# Generated by Django 6.0.3 on 2026-04-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blog',
            name='blogs_blog_categor_e4c63b_idx',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
