# Generated by Django 6.0.3 on 2026-05-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blog_blogs_blog_categor_e4c63b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='view_count',
        ),
        migrations.DeleteModel(
            name='BlogView',
        ),
    ]
