# Generated by Django 6.0.3 on 2026-05-04 12:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('language', 'Language Consultation'), ('astrology', 'Astrology Reading'), ('general', 'General Consultancy')], max_length=20)),
                ('service_type', models.CharField(max_length=100)),
                ('service_title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('price_per_session', models.DecimalField(decimal_places=2, max_digits=8)),
                ('session_duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('what_you_provide_in_session', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('certificates', models.JSONField(default=list)),
                ('about', models.TextField(blank=True)),
                ('teaching_languages', models.JSONField(default=list)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('native_language', models.CharField(blank=True, max_length=50, null=True)),
                ('learning_language', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Main topic or theme of the conversation', max_length=200)),
                ('transcription', models.JSONField(default=dict, help_text='JSON object containing conversation transcription data')),
                ('native_language', models.CharField(help_text="User's native language", max_length=50)),
                ('target_language', models.CharField(help_text='Language being learned/practiced', max_length=50)),
                ('conversation_type', models.CharField(choices=[('language', 'Language Consultation'), ('astrological', 'Astrological Consultation')], default='language', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Conversation duration in minutes', null=True)),
                ('ai_feedback', models.JSONField(blank=True, default=dict, help_text='AI-generated feedback and analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
