# Generated by Django 6.0.3 on 2026-05-04 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='participant1',
            field=models.ForeignKey(db_column='participant1', on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_participant1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='participant2',
            field=models.ForeignKey(db_column='participant2', on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_participant2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.chat'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gig',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='accounts.teacherprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='voiceconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('participant1', 'participant2')},
        ),
        migrations.AlterUniqueTogether(
            name='gig',
            unique_together={('teacher', 'category')},
        ),
        migrations.AddIndex(
            model_name='voiceconversation',
            index=models.Index(fields=['user', '-created_at'], name='accounts_vo_user_id_636d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceconversation',
            index=models.Index(fields=['target_language', '-created_at'], name='accounts_vo_target__a90820_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceconversation',
            index=models.Index(fields=['conversation_type', '-created_at'], name='accounts_vo_convers_c3ad31_idx'),
        ),
    ]
