# Generated by Django 5.2.4 on 2025-08-02 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role_chat_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('language', 'Language Consultation'), ('astrological', 'Astrological Consultation')], max_length=20)),
                ('service_type', models.CharField(max_length=100)),
                ('service_title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('price_per_session', models.DecimalField(decimal_places=2, max_digits=8)),
                ('session_duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('what_you_provide_in_session', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='accounts.teacherprofile')),
            ],
            options={
                'unique_together': {('teacher', 'category')},
            },
        ),
    ]
