# Generated by Django 5.2.4 on 2025-08-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_gig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='certificates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
