# Generated by Django 5.2.4 on 2025-08-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_teacherprofile_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='certificates',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='qualification',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
