# Generated by Django 5.2.4 on 2025-08-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_teacherprofile_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
    ]
