# Generated by Django 5.2.4 on 2025-08-09 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_gig_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Main topic or theme of the conversation', max_length=200)),
                ('transcription', models.TextField(help_text='Full transcription of the voice conversation')),
                ('native_language', models.CharField(help_text="User's native language", max_length=50)),
                ('target_language', models.CharField(help_text='Language being learned/practiced', max_length=50)),
                ('conversation_type', models.CharField(choices=[('practice', 'Language Practice'), ('lesson', 'Language Lesson'), ('conversation', 'Free Conversation'), ('assessment', 'Language Assessment'), ('pronunciation', 'Pronunciation Practice'), ('vocabulary', 'Vocabulary Building'), ('grammar', 'Grammar Practice')], default='practice', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Conversation duration in minutes', null=True)),
                ('ai_feedback', models.JSONField(blank=True, default=dict, help_text='AI-generated feedback and analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_vo_user_id_636d2e_idx'), models.Index(fields=['target_language', '-created_at'], name='accounts_vo_target__a90820_idx'), models.Index(fields=['conversation_type', '-created_at'], name='accounts_vo_convers_c3ad31_idx')],
            },
        ),
    ]
