# Generated by Django 5.2.4 on 2025-08-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_voiceconversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceconversation',
            name='conversation_type',
            field=models.CharField(choices=[('language', 'Language Consultation'), ('astrological', 'Astrological Consultation')], default='language', max_length=20),
        ),
    ]
