# Generated by Django 5.2.4 on 2025-08-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_convert_transcription_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceconversation',
            name='transcription',
            field=models.JSONField(default=dict, help_text='JSON object containing conversation transcription data'),
        ),
    ]
