# Generated by Django 5.2.4 on 2025-09-13 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_transcription_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.chat'),
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat',
            new_name='chat_id',
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender_id',
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='chat',
            table='chats',
        ),
        migrations.AlterModelTable(
            name='message',
            table='messages',
        ),
    ]
