# Generated by Django 5.2.4 on 2025-10-07 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_message_chat_rename_chat_message_chat_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='participant1',
            field=models.ForeignKey(db_column='participant1', on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_participant1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='participant2',
            field=models.ForeignKey(db_column='participant2', on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_participant2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('language', 'Language Consultation'), ('astrology', 'Astrology Reading'), ('general', 'General Consultancy')], max_length=20),
        ),
    ]
