# Generated by Django 6.0.3 on 2026-04-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_chat_participant1_alter_chat_participant2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
