# Generated by Django 6.0.3 on 2026-05-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teaching_languages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='qualification',
            field=models.TextField(blank=True),
        ),
    ]
