# Generated by Django 6.0.3 on 2026-05-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_teacherprofile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('BOTH', 'Both Student and Teacher'), ('ADMIN', 'Administrator')], max_length=20),
        ),
    ]
