import logging
import time
import pytz
from datetime import datetime

logger = logging.getLogger(__name__)

def generate_all_insights_async(birth_profile_id: int):
    """
    Background task to generate all astrology insights for a given BirthProfile.
    Uses time.sleep to avoid hitting Gemini AI rate limits.
    """
    from astrology.models import BirthProfile, NatalChartCache, TransitCache, AstrologyInsight
    from astrology.services import AstrologyAPIClient, GeminiAIService

    logger.info(f"Starting background async task to generate insights for BirthProfile ID: {birth_profile_id}")

    try:
        profile = BirthProfile.objects.select_related("user").get(id=birth_profile_id)
    except BirthProfile.DoesNotExist:
        logger.error(f"Generate Insights Task Failed: BirthProfile {birth_profile_id} not found.")
        return

    client = AstrologyAPIClient()

    # 1. Fetch base Natal Chart Data
    try:
        birth_details = client.get_birth_details(profile)
        divisional = client.get_divisional_chart(profile)

        # Update Timezone based on API response
        timezone_str = (
            birth_details.get("data", {})
            .get("calculation_info", {})
            .get("location", {})
            .get("timezone", "")
        )
        if timezone_str and not profile.timezone_str:
            profile.timezone_str = timezone_str
            profile.save(update_fields=["timezone_str"])

        # Cache the base data
        natal_cache, _ = NatalChartCache.objects.update_or_create(
            birth_profile=profile,
            defaults={
                "birth_details_data": birth_details,
                "divisional_data": divisional,
            }
        )
    except Exception as e:
        logger.error(f"Task Failed: Could not fetch base natal info for profile {birth_profile_id}. Error: {str(e)}")
        return

    # 2. Fetch extended data required by various Gemini prompts
    try:
        try:
            ashtakvarga = client.get_ashtakvarga(profile)
        except Exception as e:
            logger.error(f"Failed fetching ashtakvarga: {e}")
            raise

        try:
            dasha = client.get_vimshottari_dasha(profile)
        except Exception as e:
            logger.error(f"Failed fetching vimshottari dasha: {e}")
            raise

        try:
            kp_system = client.get_kp_system(profile)
        except Exception as e:
            logger.error(f"Failed fetching kp system: {e}")
            raise

        try:
            transit_data = client.get_transit(profile)
        except Exception as e:
            logger.error(f"Failed fetching transit data: {e}")
            raise

        # Update natal cache with extended data
        natal_cache.ashtakvarga_data = ashtakvarga
        natal_cache.dasha_data = dasha
        natal_cache.kp_data = kp_system
        natal_cache.save()

        # Update Transit Cache (valid for current day)
        tz = pytz.timezone(profile.timezone_str) if profile.timezone_str else pytz.utc
        today_local = datetime.now(tz).date()
        
        TransitCache.objects.update_or_create(
            birth_profile=profile,
            cached_for_date=today_local,
            defaults={
                "transit_data": transit_data,
            }
        )
    except Exception as e:
        logger.error(f"Task Failed: Could not fetch extended API info for profile {birth_profile_id}. Error: {str(e)}")
        return

    # 3. Assemble complete data structure to pass to Gemini
    data_to_pass = {
        "birth_details": natal_cache.birth_details_data,
        "divisional_data": natal_cache.divisional_data,
        "ashtakvarga": natal_cache.ashtakvarga_data,
        "dasha": natal_cache.dasha_data,
        "kp_system": natal_cache.kp_data,
        "transits": transit_data,
    }

    # 4. Iterate over all valid categories
    categories = [c[0] for c in AstrologyInsight.CATEGORY_CHOICES]
    logger.info(f"Generating {len(categories)} insights for profile {birth_profile_id}...")

    success_count = 0
    from django.core.cache import cache

    for category in categories:
        # Check if insight already exists to avoid redundant calls
        if AstrologyInsight.objects.filter(birth_profile=profile, category=category).exists():
            continue

        lock_key = f"generating_insight_{profile.id}_{category}"
        if cache.get(lock_key):
            # Currently being generated by a foreground view, skip it
            continue
        
        # Grab the lock
        cache.set(lock_key, True, timeout=60)

        try:
            logger.info(f"Generating insight: {category} for profile {birth_profile_id}")
            generated_text = GeminiAIService.generate_insight(category, data_to_pass)
            
            AstrologyInsight.objects.create(
                birth_profile=profile, 
                category=category, 
                insight_text=generated_text
            )
            success_count += 1
            logger.info(f"Successfully generated and cached insight: {category}")
            
        except Exception as e:
            logger.error(f"Failed to generate insight '{category}' for profile {birth_profile_id}: {str(e)}")
            # Continue to the next category even if one fails
        finally:
            cache.delete(lock_key)

        # Apply a structured delay to prevent hitting Gemini API rate limits (15 Requests Per Minute)
        # Sleeping for 4.5 seconds guarantees we stay comfortably under the limit (~13 RPM)
        time.sleep(4.5)

    logger.info(f"Finished background insight generation. Total successful: {success_count}/{len(categories)}.")
