# Generated by Django 5.2.4 on 2025-08-27 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_transcription_field_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Campaign title for reference', max_length=200)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('content', models.TextField(help_text='Full custom email message content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', help_text='Current status of the campaign', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0, help_text='Total number of students this campaign was sent to')),
                ('from_name', models.CharField(blank=True, help_text="Sender name (defaults to teacher's name)", max_length=100)),
                ('from_email', models.EmailField(blank=True, help_text="Sender email (defaults to teacher's email)", max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the campaign was actually sent', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this campaign')),
                ('teacher', models.ForeignKey(help_text='Teacher who created this campaign', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name': 'Email Campaign',
                'verbose_name_plural': 'Email Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(help_text="Student's email address", max_length=254)),
                ('student_name', models.CharField(help_text="Student's full name", max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('resend_email_id', models.CharField(blank=True, help_text='Resend email ID for tracking', max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['sent_at'],
                'unique_together': {('campaign', 'student_email')},
            },
        ),
    ]
