# Generated by Django 6.0.3 on 2026-05-04 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_recurring', models.BooleanField(default=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Teacher availabilities',
            },
        ),
        migrations.CreateModel(
            name='SessionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, default=1.0, help_text='Session duration in hours', max_digits=5)),
                ('scheduled_datetime', models.DateTimeField(blank=True, help_text='When the session is scheduled', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20)),
                ('reschedule_request_status', models.CharField(choices=[('NONE', 'No Reschedule Request'), ('PENDING', 'Reschedule Pending Confirmation'), ('CONFIRMED', 'Reschedule Confirmed'), ('DECLINED', 'Reschedule Declined')], default='NONE', help_text='Status of reschedule request', max_length=20)),
                ('reschedule_requested_by', models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], help_text='Who requested the reschedule', max_length=20, null=True)),
                ('previous_reschedule_request_status', models.CharField(choices=[('NONE', 'No Previous Request'), ('CONFIRMED', 'Previous Request Confirmed'), ('DECLINED', 'Previous Request Declined')], default='NONE', help_text='Status of the previous reschedule request (for historical tracking)', max_length=20)),
                ('reschedule_request_start_time', models.DateTimeField(blank=True, help_text='Requested new start time for reschedule', null=True)),
                ('reschedule_request_end_time', models.DateTimeField(blank=True, help_text='Requested new end time for reschedule', null=True)),
                ('reschedule_request_reason', models.TextField(blank=True, help_text='Reason for the reschedule request')),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=500, null=True)),
                ('zoom_join_url', models.URLField(blank=True, max_length=500, null=True)),
                ('zoom_start_url', models.URLField(blank=True, max_length=500, null=True)),
                ('zoom_password', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('gig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.gig')),
            ],
        ),
    ]
