# Generated by Django 5.2.4 on 2025-08-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='zoom_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='zoom_start_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
