# Generated by Django 5.2.4 on 2025-08-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_sessionbooking_zoom_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbooking',
            name='zoom_join_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='zoom_start_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
