# Generated by Django 5.2.4 on 2025-09-09 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_transcription_field_type'),
        ('bookings', '0003_alter_sessionbooking_zoom_join_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Session duration in hours', max_digits=5),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='gig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.gig'),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, help_text='When the session is scheduled', null=True),
        ),
    ]
