# Generated by Django 5.2.4 on 2025-09-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_sessionbooking_duration_hours_sessionbooking_gig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='reschedule_request_status',
            field=models.CharField(choices=[('NONE', 'No Reschedule Request'), ('PENDING', 'Reschedule Pending Confirmation'), ('CONFIRMED', 'Reschedule Confirmed'), ('DECLINED', 'Reschedule Declined')], default='NONE', help_text='Status of reschedule request', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='reschedule_requested_by',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], help_text='Who requested the reschedule', max_length=20, null=True),
        ),
    ]
