# Generated by Django 5.2.4 on 2025-09-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_sessionbooking_reschedule_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='previous_reschedule_request_status',
            field=models.CharField(choices=[('NONE', 'No Previous Request'), ('CONFIRMED', 'Previous Request Confirmed'), ('DECLINED', 'Previous Request Declined')], default='NONE', help_text='Status of the previous reschedule request (for historical tracking)', max_length=20),
        ),
    ]
