# Generated by Django 5.2.4 on 2025-09-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_sessionbooking_previous_reschedule_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='reschedule_request_end_time',
            field=models.DateTimeField(blank=True, help_text='Requested new end time for reschedule', null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='reschedule_request_reason',
            field=models.TextField(blank=True, help_text='Reason for the reschedule request'),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='reschedule_request_start_time',
            field=models.DateTimeField(blank=True, help_text='Requested new start time for reschedule', null=True),
        ),
    ]
