# Generated by Django 6.0.3 on 2026-04-29 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_sessionbooking_reschedule_request_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionFeedback',
        ),
    ]
